export const coursesStat = [
  {
    name: "Начальный Татарский",
    stat: 85,
    value: "значение",
  },
];

export const resultData = {
  name: "Общая правильность",
  stat: 85,
  value: "Выше чем у 90% учеников",
};

export const alphaBet = {
  А: "https://tatarby.shmyaks.ru/alphabet/a.MP3",
  Ә: "https://tatarby.shmyaks.ru/alphabet/%D3%99.MP3",
  Б: "https://tatarby.shmyaks.ru/alphabet/%D0%B1.MP3",
  В: "https://tatarby.shmyaks.ru/alphabet/%D0%B2.MP3",
  Г: "https://tatarby.shmyaks.ru/alphabet/%D0%B3.MP3",
  Д: "https://tatarby.shmyaks.ru/alphabet/%D0%B4.MP3",
  Е: "https://tatarby.shmyaks.ru/alphabet/%D0%B5.MP3",
  Ё: "https://tatarby.shmyaks.ru/alphabet/%D1%91.MP3",
  Ж: "https://tatarby.shmyaks.ru/alphabet/%D0%B6.MP3",
  Җ: "https://tatarby.shmyaks.ru/alphabet/%D2%97.MP3",
  З: "https://tatarby.shmyaks.ru/alphabet/%D0%B7.MP3",
  И: "https://tatarby.shmyaks.ru/alphabet/%D0%B8.MP3",
  Й: "https://tatarby.shmyaks.ru/alphabet/%D0%B9.MP3",
  К: "https://tatarby.shmyaks.ru/alphabet/%D0%BA.MP3",
  Л: "https://tatarby.shmyaks.ru/alphabet/%D0%BB.MP3",
  М: "https://tatarby.shmyaks.ru/alphabet/%D0%BC.MP3",
  Н: "https://tatarby.shmyaks.ru/alphabet/%D0%BD.MP3",
  Ң: "https://tatarby.shmyaks.ru/alphabet/%D2%A2.MP3",
  О: "https://tatarby.shmyaks.ru/alphabet/%D0%BE.MP3",
  Ө: "https://tatarby.shmyaks.ru/alphabet/%D3%A9.MP3",
  П: "https://tatarby.shmyaks.ru/alphabet/%D0%BF.MP3",
  Р: "https://tatarby.shmyaks.ru/alphabet/%D1%80.MP3",
  С: "https://tatarby.shmyaks.ru/alphabet/%D1%81.MP3",
  Т: "https://tatarby.shmyaks.ru/alphabet/%D1%82.MP3",
  У: "https://tatarby.shmyaks.ru/alphabet/%D1%83.MP3",
  Ү: "https://tatarby.shmyaks.ru/alphabet/%D2%AF.MP3",
  Ф: "https://tatarby.shmyaks.ru/alphabet/%D1%84.MP3",
  Х: "https://tatarby.shmyaks.ru/alphabet/%D1%85.MP3",
  Һ: "https://tatarby.shmyaks.ru/alphabet/%D2%BB.MP3",
  Ц: "https://tatarby.shmyaks.ru/alphabet/%D1%86.MP3",
  Ч: "https://tatarby.shmyaks.ru/alphabet/%D1%87.MP3",
  Ш: "https://tatarby.shmyaks.ru/alphabet/%D1%88.MP3",
  Щ: "https://tatarby.shmyaks.ru/alphabet/%D1%89.MP3",
  Ъ: "https://tatarby.shmyaks.ru/alphabet/%D1%8A.MP3",
  Ы: "https://tatarby.shmyaks.ru/alphabet/%D1%8B.MP3",
  Ь: "https://tatarby.shmyaks.ru/alphabet/%D1%8C.MP3",
  Э: "https://tatarby.shmyaks.ru/alphabet/%D1%8D.MP3",
  Ю: "https://tatarby.shmyaks.ru/alphabet/%D1%8E.MP3",
  Я: "https://tatarby.shmyaks.ru/alphabet/%D1%8F.MP3",
};
